spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-dev-client2

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:enjoy@localhost:7001/eureka
  register-with-eureka: false

info:
  app.name: microcloud-config-client-dev2
  company.name: dev_enjoy2


---
server:
  port: 8202

spring:
  profiles: beta
  application:
      name: microconfig-test-client2

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:enjoy@localhost:7001/eureka
  register-with-eureka: false
  
info:
  app.name: microcloud-config-client-beta2
  company.name: beta_enjo2
